### ISSUE TITLE
want create  voting app for college post

### ISSUE THREAD

**Issue by Rajdeep-4321** [mahmudahsan/flutter_firebase_vote#3]
how to create voting app for college like general secratary and all...and a user can only give vote once

**Comment by mahmudahsan** [comment]
well, in that case you have to implement the code and before casting vote you have to check whether same user voted before or not.

**Comment by Rajdeep-4321** [comment]
how to check that??

**Comment by Rajdeep-4321** [comment]
it's urgent for me...
is it possible then how i can implement in your code, that a user can only vote once..

**Comment by mahmudahsan** [comment]
Basically you need to create another table in firestore, and when a user casts a vote you have to save the user UID and voteId in that table. And when every time a user wants to casts vote, you have to check whether that particular user already has given a vote or not.

**Comment by Rajdeep-4321** [comment]
as i am new to fkutter as well as firebase..
how to store uid and voteid in firestore and check whether voter voted or not????
